apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: student-management
data:
  MYSQL_DATABASE: studentdb
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: student
  MYSQL_PASSWORD: student123
