apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: student-management
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8089"
  SERVER_SERVLET_CONTEXT_PATH: "/student"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/studentdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "student"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQLDialect"
